import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { ArrowRight, TrendingUp, Map, Users, DollarSign, FileText, Network, Building2 } from "lucide-react"
import Link from "next/link"

export default function HomePage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-gray-200">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-[#003366] flex items-center justify-center">
              <div className="w-3 h-3 rounded-full bg-white" />
            </div>
            <div className="flex flex-col leading-tight">
              <span className="text-sm font-bold text-[#003366]">Freedom Cities</span>
              <span className="text-xs font-semibold text-[#003366]">Coalition</span>
            </div>
          </div>

          <nav className="hidden md:flex items-center gap-6">
            <Link href="#why" className="text-sm text-gray-700 hover:text-gray-900">
              Why Freedom Cities?
            </Link>
            <Link href="#policy" className="text-sm text-gray-700 hover:text-gray-900">
              Policy Options
            </Link>
            <Button className="bg-[#003366] hover:bg-[#004080] text-white">Join the Coalition</Button>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-5xl md:text-6xl font-bold mb-6 text-balance">
          Unleash
          <br />
          <span className="text-[#0080FF]">American Dynamism</span>
          <br />
          with Freedom Cities
        </h1>
        <p className="text-gray-600 text-lg max-w-2xl mx-auto mb-8 text-pretty">
          Freedom Cities will revitalize the American economy, nearshore American manufacturing, and unleash the
          potential of American entrepreneurs.
        </p>
        <Button className="bg-[#003366] hover:bg-[#004080] text-white">
          Join the Coalition
          <ArrowRight className="ml-2 h-4 w-4" />
        </Button>
      </section>

      {/* Why Freedom Cities Section */}
      <section id="why" className="bg-gray-50 py-16">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4">Why Freedom Cities?</h2>
          <p className="text-gray-600 text-center max-w-3xl mx-auto mb-12 text-pretty">
            Freedom Cities are a once-in-a-generation opportunity to solve the housing crisis, bring American
            manufacturing home, and unleash the full potential of American entrepreneurs through the creation of special
            districts called Prosperity Zones.
          </p>

          {/* Stats Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Card className="p-6 bg-white border border-gray-200">
              <TrendingUp className="h-8 w-8 text-[#0080FF] mb-4" />
              <div className="text-3xl font-bold text-[#0080FF] mb-2">$1.9T</div>
              <div className="font-semibold mb-2">Projected economic impact</div>
              <p className="text-sm text-gray-600">
                Total potential economic growth generated by improved regulatory environment
              </p>
            </Card>

            <Card className="p-6 bg-white border border-gray-200">
              <Map className="h-8 w-8 text-[#0080FF] mb-4" />
              <div className="text-3xl font-bold text-[#0080FF] mb-2">50</div>
              <div className="font-semibold mb-2">States which could build Freedom Cities</div>
              <p className="text-sm text-gray-600">Located strategically throughout America's heartland</p>
            </Card>

            <Card className="p-6 bg-white border border-gray-200">
              <Users className="h-8 w-8 text-[#0080FF] mb-4" />
              <div className="text-3xl font-bold text-[#0080FF] mb-2">250,000+</div>
              <div className="font-semibold mb-2">Potential residents of Freedom Cities by 2035</div>
              <p className="text-sm text-gray-600">Unleashing the potential of Americans from all walks of life</p>
            </Card>

            <Card className="p-6 bg-white border border-gray-200">
              <DollarSign className="h-8 w-8 text-[#0080FF] mb-4" />
              <div className="text-3xl font-bold text-[#0080FF] mb-2">$1T+</div>
              <div className="font-semibold mb-2">Wealth created per city</div>
              <p className="text-sm text-gray-600">
                Each freedom city can unleash trillions of dollars in wealth creation over the next decade
              </p>
            </Card>
          </div>
        </div>
      </section>

      {/* Support Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-start">
            <div>
              <h2 className="text-3xl font-bold mb-4">Ready to Support American Innovation?</h2>
              <p className="text-gray-600 mb-6 text-pretty">
                Join our coalition to help build the future of American cities. Together, we can create new
                opportunities for manufacturing, technology, and sustainable development.
              </p>
              <Button className="bg-[#0080FF] hover:bg-[#0066CC] text-white">
                Join the Coalition
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Key Benefits</h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-[#0080FF] mt-1">•</span>
                  <span className="text-gray-700">Improved governance for faster growth and innovation</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#0080FF] mt-1">•</span>
                  <span className="text-gray-700">Locations across the US starting in greenfield sites</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#0080FF] mt-1">•</span>
                  <span className="text-gray-700">
                    Solves the housing crisis by building thousands of new housing units
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#0080FF] mt-1">•</span>
                  <span className="text-gray-700">Optimal solution for nearshoring American manufacturing</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Policy Options Section */}
      <section id="policy" className="bg-gray-50 py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mb-12">
            <h2 className="text-3xl font-bold mb-4">Public Policy Options</h2>
            <p className="text-gray-600 mb-6 text-pretty">
              There are numerous ways to achieve transformative impact with freedom cities, each with their own benefits
              and drawbacks.
            </p>
            <Button
              variant="outline"
              className="border-[#003366] text-[#003366] hover:bg-[#003366] hover:text-white bg-transparent"
            >
              Learn More
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>

          <div className="space-y-6 max-w-4xl">
            <Card className="p-6 bg-white border border-gray-200">
              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 rounded-lg bg-blue-50 flex items-center justify-center">
                    <FileText className="h-6 w-6 text-[#0080FF]" />
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-lg mb-2">Executive Order Approach</h3>
                  <p className="text-gray-600 text-pretty">
                    Rapid implementation through presidential designation of specific geographic areas as Freedom Cities
                    Zones with optimal federal regulatory enforcement.
                  </p>
                </div>
              </div>
            </Card>

            <Card className="p-6 bg-white border border-gray-200">
              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 rounded-lg bg-blue-50 flex items-center justify-center">
                    <Network className="h-6 w-6 text-[#0080FF]" />
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-lg mb-2">Interstate Compact Approach</h3>
                  <p className="text-gray-600 text-pretty">
                    States enter into a durable agreement, with Congressional consent, to create special regulatory and
                    tax zones with stronger legal foundations.
                  </p>
                </div>
              </div>
            </Card>

            <Card className="p-6 bg-white border border-gray-200">
              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 rounded-lg bg-blue-50 flex items-center justify-center">
                    <Building2 className="h-6 w-6 text-[#0080FF]" />
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-lg mb-2">Federal Enclave Approach</h3>
                  <p className="text-gray-600 text-pretty">
                    Congress establishes special jurisdictional zones with comprehensive regulatory frameworks and
                    strongest legal authority.
                  </p>
                </div>
              </div>
            </Card>
          </div>

          <div className="mt-12 max-w-3xl">
            <h3 className="font-semibold text-lg mb-4">Why These Reforms Matter</h3>
            <p className="text-gray-600 mb-4 text-pretty">
              Current regulations and bureaucratic processes cost the American economy nearly $2T a year. Freedom Cities
              coupled with deep regulatory and governance reform could unleash the suppressed potential of the American
              economy.
            </p>
            <p className="text-gray-600 text-pretty">
              By streamlining governance and creating clear legal frameworks, we can accelerate the development of new
              urban centers that drive economic growth and technological advancement.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-[#003366] py-20 text-white text-center">
        <div className="container mx-auto px-4">
          <h2 className="text-4xl md:text-5xl font-bold mb-6 text-balance">Ready to unleash American excellence?</h2>
          <p className="text-lg text-blue-100 max-w-2xl mx-auto mb-8 text-pretty">
            Join a coalition of leaders, innovators, and visionaries building the future of American cities.
          </p>
          <Button className="bg-white text-[#003366] hover:bg-gray-100">
            Join the Coalition
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-black text-white py-12">
        <div className="container mx-auto px-4">
          <div className="mb-8">
            <h3 className="text-3xl font-bold mb-4">Ignite the future of American cities.</h3>
            <p className="text-gray-400 mb-6 max-w-xl">
              Join to show your support and protect the future of American innovation.
            </p>
            <Button className="bg-[#0080FF] hover:bg-[#0066CC] text-white">Join the Coalition</Button>
          </div>

          <div className="flex flex-wrap gap-6 text-sm text-gray-400 mb-6">
            <Link href="#" className="hover:text-white">
              Terms of Service
            </Link>
            <Link href="#" className="hover:text-white">
              Privacy Policy
            </Link>
          </div>

          <div className="text-xs text-gray-500 border-t border-gray-800 pt-6">
            <p>The Freedom Cities Coalition is a project of NewKey Capital LLC and affiliates.</p>
            <p className="mt-1">© All Rights Reserved 2025</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
